python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_L_freeze_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_1007 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision/train/saved_models/model_step_1007.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_1007 2>&1
python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_L_freeze_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_2014 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_1007/train/saved_models/model_step_2014.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_2014 2>&1
python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_L_freeze_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_3021 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_1007/train/saved_models/model_step_3021.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_3021 2>&1
python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_L_freeze_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_4028 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_3021/train/saved_models/model_step_4028.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_4028 2>&1
python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_L_freeze_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_5035 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_3021/train/saved_models/model_step_5035.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_5035 2>&1
python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_L_freeze_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_6042 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_3021/train/saved_models/model_step_6042.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_6042 2>&1
python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_L_freeze_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_7049 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_6042/train/saved_models/model_step_7049.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_7049 2>&1
python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_L_freeze_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_8056 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_6042/train/saved_models/model_step_8056.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_L_Freeze_Vision_ckpt_model_step_8056 2>&1


python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_B_freeze_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision_ckpt_model_step_6042 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision_ckpt_model_step_3021/train/saved_models/model_step_6042.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision_ckpt_model_step_6042 2>&1
python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_B_freeze_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision_ckpt_model_step_5035 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision_ckpt_model_step_3021/train/saved_models/model_step_5035.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision_ckpt_model_step_5035 2>&1
python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_B_freeze_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision_ckpt_model_step_4028 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision_ckpt_model_step_3021/train/saved_models/model_step_4028.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision_ckpt_model_step_4028 2>&1
python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_B_freeze_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision_ckpt_model_step_3021 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision/train/saved_models/model_step_3021.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision_ckpt_model_step_3021 2>&1
python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_B_freeze_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision_ckpt_model_step_2014 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision/train/saved_models/model_step_2014.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision_ckpt_model_step_2014 2>&1
python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_B_freeze_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision_ckpt_model_step_1007 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision/train/saved_models/model_step_1007.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_B_Freeze_Vision_ckpt_model_step_1007 2>&1


python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_no_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision_ckpt_model_step_6042 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision_ckpt_model_step_3021/train/saved_models/model_step_6042.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision_ckpt_model_step_6042 2>&1
python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_no_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision_ckpt_model_step_5035 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision_ckpt_model_step_3021/train/saved_models/model_step_5035.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision_ckpt_model_step_5035 2>&1
python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_no_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision_ckpt_model_step_4028 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision_ckpt_model_step_3021/train/saved_models/model_step_4028.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision_ckpt_model_step_4028 2>&1
python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_no_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision_ckpt_model_step_3021 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision/train/saved_models/model_step_3021.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision_ckpt_model_step_3021 2>&1
python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_no_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision_ckpt_model_step_2014 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision/train/saved_models/model_step_2014.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision_ckpt_model_step_2014 2>&1
python src/main.py --config configs/Rerank/initial_experiments/okvqa_full_context_rerank_no_vision.jsonnet --mode test --experiment_name TEST_OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision_ckpt_model_step_1007 --tags "OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision" "test" --opts train.load_model_path="/home/fz288/rds/hpc-work/PreFLMR/experiments/OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision/train/saved_models/model_step_1007.ckpt" > log_TEST_OKVQA_FLMRQuery_Full_Context_Rerank_No_Vision_ckpt_model_step_1007 2>&1

source hpc/q_all.sh