
// local distillation_model_ckpt = "LinWeizheDragon/PreFLMR_ViT-G";
// local image_processor_name = "laion/CLIP-ViT-bigG-14-laion2B-39B-b160k";
local distillation_model_ckpt = "/root/rds/data/models/LinWeizheDragon--PreFLMR_ViT-L";
local image_processor_name = "/root/rds/data/models/openai--clip-vit-large-patch14";
local num_negatives = 4;
local num_distillation_data = 100000;

local merge_data_pipeline = {
  name: 'MergeDataPipeline',
  regenerate: false,
  do_inspect: true,
  transforms: {
    'process:LoadCCData': {
      transform_name: 'LoadPreprocessedData_v2',
      regenerate: false,
      cache: true,
      setup_kwargs: {
        data_path: "/root/rds/data/models/BByrneLab--multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR///CC_data",
        passage_path: "/root/rds/data/models/BByrneLab--multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR///CC_passages",
        image_root_folder: "/root/rds/data/CC3M/LLaVA-CC3M-Pretrain-595K/images",
      },
    },
    'process:LoadLLaVaData': {
      transform_name: 'LoadPreprocessedData_v2',
      regenerate: false,
      cache: true,
      setup_kwargs: {
        data_path: "/root/rds/data/models/BByrneLab--multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR///LLaVA_data",
        passage_path: "/root/rds/data/models/BByrneLab--multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR///LLaVA_passages",
        image_root_folder: "/root/rds/data/OKVQA",
        add_instruction: [
          "Provide a brief description of the image along with the following question:",
          "Provide a concise explanation of the image along with the following question:",
        ],
      },
    },
    'process:LoadMSMARCOData': {
      transform_name: 'LoadPreprocessedData_v2',
      regenerate: false,
      cache: true,
      setup_kwargs: {
        data_path: "/root/rds/data/models/BByrneLab--multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR///MSMARCO_data",
        passage_path: "/root/rds/data/models/BByrneLab--multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR///MSMARCO_passages",
      },
    },
    'process:LoadOvenData': {
      transform_name: 'LoadPreprocessedData_v2',
      regenerate: false,
      cache: true,
      setup_kwargs: {
        data_path: "/root/rds/data/models/BByrneLab--multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR///OVEN_data",
        passage_path: "/root/rds/data/models/BByrneLab--multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR///OVEN_passages",
        image_root_folder: "/root/rds/data/OVEN",
        add_instruction: [
          "Using the provided image, obtain documents that address the subsequent question: ",
          "Retrieve documents that provide an answer to the question alongside the image: ",
          "Extract documents linked to the question provided in conjunction with the image: ",
          "Utilizing the given image, obtain documents that respond to the following question: ",
          "Using the given image, access documents that provide insights into the following question: ",
          "Obtain documents that correspond to the inquiry alongside the provided image: ",
          "With the provided image, gather documents that offer a solution to the question: ",
          "Utilizing the given image, obtain documents that respond to the following question: ",
        ],
      },
    },
    // 'process:LoadWITGeneratedQuestionsData': {
    //   transform_name: 'LoadPreprocessedData_v2',
    //   regenerate: false,
    //   cache: true,
    //   setup_kwargs: {
    //     data_path: "/home/ubuntu/data/wit/PrepareWIT_Generated_Questions_38K.hf",
    //     passage_path: "/home/ubuntu/data/wit/SplitWIT_Generated_Questions_38K.hf",
    //     // shuffle_splits: ['train', 'valid'],
    //     // num_data: {'train': -1, 'valid': 10000},
    //     use_generated_questions: true,
    //     add_question_id_prefix: "WITQ",
    //     add_instruction: [
    //       "Using the provided image, obtain documents that address the subsequent question: ",
    //       "Retrieve documents that provide an answer to the question alongside the image: ",
    //       "Extract documents linked to the question provided in conjunction with the image: ",
    //       "Utilizing the given image, obtain documents that respond to the following question: ",
    //       "Using the given image, access documents that provide insights into the following question: ",
    //       "Obtain documents that correspond to the inquiry alongside the provided image: ",
    //       "With the provided image, gather documents that offer a solution to the question: ",
    //       "Utilizing the given image, obtain documents that respond to the following question: ",
    //     ],
    //   },
    // },
    // 'process:LoadInfoSeekData': {
    //   transform_name: 'LoadPreprocessedData_v2',
    //   regenerate: false,
    //   cache: true,
    //   setup_kwargs: {
    //     data_path: "/home/ubuntu/additional_data/projects/KBVQA/cache/InfoSeekDataPipeline/process:MergeDataColumns-16198829ca9181f8d8443592a1d2c77f.hf",
    //     passage_path: "/home/ubuntu/additional_data/projects/KBVQA/cache/InfoSeekDataPipeline/process:ReduceWikipediaPassagesSizeForInfoSeek-45fd077e40519f6556958a1004ed7b0a.hf",
    //     use_filtered_passages: true,
    //     shuffle_splits: ['train'],
    //     num_data: {'train': 100000, 'valid': -1},
    //     add_instruction: [
    //       "Using the provided image, obtain documents that address the subsequent question: ",
    //       "Retrieve documents that provide an answer to the question alongside the image: ",
    //       "Extract documents linked to the question provided in conjunction with the image: ",
    //       "Utilizing the given image, obtain documents that respond to the following question: ",
    //       "Using the given image, access documents that provide insights into the following question: ",
    //       "Obtain documents that correspond to the inquiry alongside the provided image: ",
    //       "With the provided image, gather documents that offer a solution to the question: ",
    //       "Utilizing the given image, obtain documents that respond to the following question: ",
    //     ],
    //   },
    // },
    'process:LoadKVQAData': {
      transform_name: 'LoadPreprocessedData_v2',
      regenerate: false,
      cache: true,
      setup_kwargs: {
        data_path: "/root/rds/data/models/BByrneLab--multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR///KVQA_data",
        passage_path: "/root/rds/data/models/BByrneLab--multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR///KVQA_passages",
        image_root_folder: "/root/rds/data/KVQA/KVQAimgs",
        add_instruction: [
          "Using the provided image, obtain documents that address the subsequent question: ",
          "Retrieve documents that provide an answer to the question alongside the image: ",
          "Extract documents linked to the question provided in conjunction with the image: ",
          "Utilizing the given image, obtain documents that respond to the following question: ",
          "Using the given image, access documents that provide insights into the following question: ",
          "Obtain documents that correspond to the inquiry alongside the provided image: ",
          "With the provided image, gather documents that offer a solution to the question: ",
          "Utilizing the given image, obtain documents that respond to the following question: ",
        ],
      },
    },
    'process:LoadEVQAData': {
      transform_name: 'LoadPreprocessedData_v2',
      regenerate: false,
      cache: true,
      setup_kwargs: {
        data_path: "/root/rds/data/models/BByrneLab--multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR///EVQA_data",
        passage_path: "/root/rds/data/models/BByrneLab--multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR///EVQA_passages",
        image_root_folder: "/root/rds/data/EVQA/images",
        add_instruction: [
          "Using the provided image, obtain documents that address the subsequent question: ",
          "Retrieve documents that provide an answer to the question alongside the image: ",
          "Extract documents linked to the question provided in conjunction with the image: ",
          "Utilizing the given image, obtain documents that respond to the following question: ",
          "Using the given image, access documents that provide insights into the following question: ",
          "Obtain documents that correspond to the inquiry alongside the provided image: ",
          "With the provided image, gather documents that offer a solution to the question: ",
          "Utilizing the given image, obtain documents that respond to the following question: ",
        ],
      },
    },
    'process:LoadOKVQAData': {
      transform_name: 'LoadPreprocessedData_v2',
      regenerate: false,
      cache: true,
      setup_kwargs: {
        data_path: "/root/rds/data/models/BByrneLab--multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR///OKVQA_data",
        passage_path: "/root/rds/data/models/BByrneLab--multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR///OKVQA_passages",
        image_root_folder: "/root/rds/data/OKVQA",
        add_instruction: [
          "Using the provided image, obtain documents that address the subsequent question: ",
          "Retrieve documents that provide an answer to the question alongside the image: ",
          "Extract documents linked to the question provided in conjunction with the image: ",
          "Utilizing the given image, obtain documents that respond to the following question: ",
          "Using the given image, access documents that provide insights into the following question: ",
          "Obtain documents that correspond to the inquiry alongside the provided image: ",
          "With the provided image, gather documents that offer a solution to the question: ",
          "Utilizing the given image, obtain documents that respond to the following question: ",
        ],
      },
    },
    'process:LoadWITData': {
      transform_name: 'LoadPreprocessedData_v2',
      regenerate: false,
      cache: true,
      setup_kwargs: {
        data_path: "/root/rds/data/models/BByrneLab--multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR///WIT_data",
        passage_path: "/root/rds/data/models/BByrneLab--multi_task_multi_modal_knowledge_retrieval_benchmark_M2KR///WIT_passages",
        image_root_folder: "/root/rds/data/WIT/images",
        add_instruction: [
          "Identify the document that is connected to this image.:",
          "Provide information about the document linked to this image.:",
          "Please describe the document that corresponds to this image.:",
          "What is the document that this image is related to?:",
          "Could you elucidate the document associated with this image?:",
          "Describe the document that accompanies this image.:",
          "Please give information on the document that goes with this image.:",
          "What document is represented by this image?:",
          "Identify the document that this image pertains to.:",
        ],
      },
    },
    // 'process:AddTextBasedVisionToInfoseek': {
    //   transform_name: 'AddTextBasedVision',
    //   input_node: 'process:LoadInfoSeekData',
    //   regenerate: false,
    //   cache: true,
    //   setup_kwargs: {
    //     splits_to_process: ["train", "valid"],
    //     caption_config: {"separation_tokens": {'start': 'Caption:', 'end': ''}},
    //     object_config: {
    //       "object_max": 40, 
    //       "attribute_max": 3, 
    //       "attribute_thres":0.05, 
    //       "ocr": 0,
    //       "separation_tokens": {'start': 'Objects:', 'sep': ',', 'end': ''}},
    //   },
    // },
    // 'process:AddInstructionToOKVQA': {
    //   transform_name: 'AddInstruction',
    //   input_node: 'process:PrepareWikipediaPassageAnnotationsForOKVQA',
    //   regenerate: false,
    //   cache: true,
    //   setup_kwargs: {
    //     splits_to_process: ["train", "valid", "test"],
    //     add_instruction: [
    //       "Using the provided image, obtain documents that address the subsequent question: ",
    //       "Retrieve documents that provide an answer to the question alongside the image: ",
    //       "Extract documents linked to the question provided in conjunction with the image: ",
    //       "Utilizing the given image, obtain documents that respond to the following question: ",
    //       "Using the given image, access documents that provide insights into the following question: ",
    //       "Obtain documents that correspond to the inquiry alongside the provided image: ",
    //       "With the provided image, gather documents that offer a solution to the question: ",
    //       "Utilizing the given image, obtain documents that respond to the following question: ",
    //     ],
    //   },
    // },
    // 'process:AddTextBasedVisionToOKVQA': {
    //   transform_name: 'AddTextBasedVision',
    //   input_node: 'process:AddInstructionToOKVQA',
    //   regenerate: false,
    //   cache: true,
    //   setup_kwargs: {
    //     splits_to_process: ["train", "valid", "test"],
    //     caption_config: {"separation_tokens": {'start': 'Caption:', 'end': ''}},
    //     object_config: {
    //       "object_max": 40, 
    //       "attribute_max": 3, 
    //       "attribute_thres":0.05, 
    //       "ocr": 1,
    //       "separation_tokens": {'start': 'Objects:', 'sep': ',', 'end': ''}},
    //   },
    // },
    'process:PrepareDistillationScoresForLLaVA': {
      transform_name: 'PrepareDistillationScores',
      regenerate: false,
      cache: true,
      input_node: 'process:LoadLLaVaData',
      setup_kwargs: {
        model_ckpt: distillation_model_ckpt,
        image_processor_name: image_processor_name,
        num_negatives: num_negatives,
        limit_num_data: num_distillation_data,
        _use_elastic_search: true,
        _index_name: "distillation_data",
        _source_name: "llava",
      },
    },
    'process:PrepareDistillationScoresForMSMARCO': {
      transform_name: 'PrepareDistillationScores',
      regenerate: false,
      cache: true,
      input_node: 'process:LoadMSMARCOData',
      setup_kwargs: {
        model_ckpt: distillation_model_ckpt,
        image_processor_name: image_processor_name,
        num_negatives: num_negatives,
        limit_num_data: num_distillation_data,
        _use_elastic_search: true,
        _index_name: "distillation_data",
        _source_name: "msmarco",
      },
    },
    'process:PrepareDistillationScoresForOven': {
      transform_name: 'PrepareDistillationScores',
      regenerate: false,
      cache: true,
      input_node: 'process:LoadOvenData',
      setup_kwargs: {
        model_ckpt: distillation_model_ckpt,
        image_processor_name: image_processor_name,
        num_negatives: num_negatives,
        limit_num_data: num_distillation_data,
        _use_elastic_search: true,
        _index_name: "distillation_data",
        _source_name: "oven",
      },
    },
    'process:PrepareDistillationScoresForKVQA': {
      transform_name: 'PrepareDistillationScores',
      regenerate: false,
      cache: true,
      input_node: 'process:LoadKVQAData',
      setup_kwargs: {
        model_ckpt: distillation_model_ckpt,
        image_processor_name: image_processor_name,
        num_negatives: num_negatives,
        limit_num_data: num_distillation_data,
        _use_elastic_search: true,
        _index_name: "distillation_data",
        _source_name: "kvqa",
      },
    },
    'process:PrepareDistillationScoresForOKVQA': {
      transform_name: 'PrepareDistillationScores',
      regenerate: false,
      cache: true,
      input_node: 'process:LoadOKVQAData',
      setup_kwargs: {
        model_ckpt: distillation_model_ckpt,
        image_processor_name: image_processor_name,
        num_negatives: num_negatives,
        limit_num_data: num_distillation_data,
        _use_elastic_search: true,
        _index_name: "distillation_data",
        _source_name: "okvqa",
      },
    },
    'process:PrepareDistillationScoresForEVQA': {
      transform_name: 'PrepareDistillationScores',
      regenerate: false,
      cache: true,
      input_node: 'process:LoadEVQAData',
      setup_kwargs: {
        model_ckpt: distillation_model_ckpt,
        image_processor_name: image_processor_name,
        num_negatives: num_negatives,
        limit_num_data: num_distillation_data,
        _use_elastic_search: true,
        _index_name: "distillation_data",
        _source_name: "evqa",
      },
    },
    'process:PrepareDistillationScoresForCC': {
      transform_name: 'PrepareDistillationScores',
      regenerate: false,
      cache: true,
      input_node: 'process:LoadCCData',
      setup_kwargs: {
        model_ckpt: distillation_model_ckpt,
        image_processor_name: image_processor_name,
        num_negatives: num_negatives,
        limit_num_data: num_distillation_data,
        _use_elastic_search: true,
        _index_name: "distillation_data",
        _source_name: "cc",
      },
    },
    'process:PrepareDistillationScoresForWIT': {
      transform_name: 'PrepareDistillationScores',
      regenerate: false,
      cache: true,
      input_node: 'process:LoadWITData',
      setup_kwargs: {
        model_ckpt: distillation_model_ckpt,
        image_processor_name: image_processor_name,
        num_negatives: num_negatives,
        limit_num_data: num_distillation_data,
        _use_elastic_search: true,
        _index_name: "distillation_data",
        _source_name: "wit",
      },
    },
    'process:ConcatenateDatasets': {
      transform_name: 'ConcatenateDatasets',
      input_node: [
        'process:PrepareDistillationScoresForWIT',
        'process:PrepareDistillationScoresForCC',
        // 'process:LoadWITData',
        // 'process:LoadCCData',
        'process:PrepareDistillationScoresForLLaVA',
        'process:PrepareDistillationScoresForMSMARCO',
        // 'process:LoadInfoSeekData',
        // 'process:AddTextBasedVisionToInfoseek',
        'process:PrepareDistillationScoresForOven',
        'process:PrepareDistillationScoresForKVQA',
        'process:PrepareDistillationScoresForOKVQA',
        'process:PrepareDistillationScoresForEVQA',
      ],
      regenerate: false,
      cache: true,
      setup_kwargs: {
        // negative_names: ["wit_passages", "cc_passages", "llava_passages", "msmarco_passages", "infoseek_passages", "oven_passages", "kvqa_passages", 'okvqa_passages', 'evqa_passages', 'witq_passages'],
        negative_names: ["wit_passages", "cc_passages", "llava_passages", "msmarco_passages", "oven_passages", "kvqa_passages", 'okvqa_passages', 'evqa_passages'],
        concat_splits: {
          'train': [true, true, true, true, true, true, 10, true],
          'valid': [true, false, true, true, false, false, true, true],
          'test': [true, false, true, true, false, false, true, true],
        },
        splits_to_process: ["train", "valid", "test"],
      },
    },
    'process:WrapOutputIntoKeys': {
      transform_name: 'WrapOutputIntoKeys',
      input_node: [
        'process:PrepareDistillationScoresForWIT',
        'process:PrepareDistillationScoresForCC',
        // 'process:LoadWITData',
        // 'process:LoadCCData',
        'process:PrepareDistillationScoresForLLaVA',
        'process:PrepareDistillationScoresForMSMARCO',
        // 'process:LoadInfoSeekData',
        // 'process:AddTextBasedVisionToInfoseek',
        'process:PrepareDistillationScoresForOven',
        'process:PrepareDistillationScoresForKVQA',
        'process:PrepareDistillationScoresForOKVQA',
        'process:PrepareDistillationScoresForEVQA',
        'process:ConcatenateDatasets',
      ],
      regenerate: true,
      cache: false,
      setup_kwargs: {
        output_keys: ["wit_data", "cc_data", "llava_data", "msmarco_data", "oven_data", "kvqa_data", "okvqa_data", 'evqa_data', "combined_data"],
      },
    },
    'process:ConcatenatePassageDatasets': {
      transform_name: 'ConcatenatePassageDatasets',
      input_node: [
        'process:PrepareDistillationScoresForWIT',
        'process:PrepareDistillationScoresForCC',
        // 'process:LoadWITData',
        // 'process:LoadCCData',
        'process:PrepareDistillationScoresForLLaVA',
        'process:PrepareDistillationScoresForMSMARCO',
        // 'process:LoadInfoSeekData',
        'process:PrepareDistillationScoresForOven',
        'process:PrepareDistillationScoresForKVQA',
        'process:PrepareDistillationScoresForOKVQA',
        'process:PrepareDistillationScoresForEVQA',
      ],
      regenerate: false,
      cache: true,
      setup_kwargs: {
        names: ["wit_passages", "cc_passages", "llava_passages", "msmarco_passages", "oven_passages", "kvqa_passages", 'okvqa_passages', 'evqa_passages'],
        concat_splits: {
          'train_passages': [true, true, true, true, true, true, true, true],
          'valid_passages': [true, false, true, true, false, false, true, true],
          'test_passages': [true, false, true, true, false, false, true, true],
        },
      },
    },
  },
};

{
  merge_data_pipeline: merge_data_pipeline,
}
